### ISSUE TITLE
文档有问题，刷新404

### ISSUE THREAD

**Issue by leotian** [gogoyqj/auto-service#25]
https://gogoyqj.github.io/auto-service/getting-started

如上

**Comment by gogoyqj** [comment]
@leotian 白嫖的服务不支持 nginx fallback，只有手动替换回 https://gogoyqj.github.io/auto-service/

**Comment by yunsii** [comment]
可以手动生成相关路由的 html 文件就可以 fallback 了，如果能从框架层面解决是最好的

**Comment by gogoyqj** [comment]
> https://gogoyqj.github.io/auto-service/getting-started
> 
> 如上

已解决 & 文档已迁移到 https://tefe.top
