### ISSUE TITLE
能否指定Ajax 接口 导入的名称 @ajax

### ISSUE THREAD

**Issue by BangXinWei** [gogoyqj/auto-service#34]
Hi，大佬们

能不能指定
import ajax, { AjaxPromise, ExtraFetchParams } from '@ajax';

'@ajax' 这个名称啊？

换成

import ajax, { AjaxPromise, ExtraFetchParams } from '@ajax11111';

维护的多个接口，需要不同的ajax，不适合写在一起

**Comment by gogoyqj** [comment]
参考这个代码 @BangXinWei 
https://github.com/e-kit/ekit/blob/master/packages/ajax/src/new-ajax.ts

**Comment by BangXinWei** [comment]
> 参考这个代码 @BangXinWei
> https://github.com/e-kit/ekit/blob/master/packages/ajax/src/new-ajax.ts

是可以的，感谢

**Comment by git-xyz** [comment]
> @BangXinWei 场景是什么？ —— 这个可以通过自定义模板实现

抱歉了大佬，模版在哪里指定

**Comment by BangXinWei** [comment]
> > @BangXinWei 场景是什么？ —— 这个可以通过自定义模板实现
> 
> 抱歉了大佬，请问模版在哪里指定，配置文件里没有看到有指定这个的地方
文档截图
![image](https://user-images.githubusercontent.com/34148401/165705936-4caed39c-9597-4792-bceb-92c1306fb807.png)
感觉autos 导出的 node 接口，有.d.ts，比cli配置文件方式，更方便写代码。

下面runkit下autos导出node模块，类型定义
https://npm.runkit.com/auto-service/lib/index.d.ts?t=1651132569291

**Comment by gogoyqj** [comment]
> > > @BangXinWei 场景是什么？ —— 这个可以通过自定义模板实现
> > 
> > 
> > 抱歉了大佬，请问模版在哪里指定，配置文件里没有看到有指定这个的地方
> 
> 文档截图 ![image](https://user-images.githubusercontent.com/34148401/165705936-4caed39c-9597-4792-bceb-92c1306fb807.png) 感觉autos 导出的 node 接口，有.d.ts，比cli配置文件方式，更方便写代码。 下面runkit下autos导出node模块，类型定义 https://npm.runkit.com/auto-service/lib/index.d.ts?t=1651132569291

-t 指定一个模板目录的绝对路径，模板可以参考 https://github.com/gogoyqj/auto-service/tree/master/plugins/typescript-tkit
