### ISSUE TITLE
modle文件缺失

### ISSUE THREAD

**Issue by flames519** [gogoyqj/auto-service#39]
1.当我单独定义include指定路径时， body和返回体的类型文件生成正常
2.当我include指定多个路径时， 部分路径只生成返回体或者只生成body的modle类型文件

**Comment by flames519** [comment]
![Uploading image.png…]()

**Comment by gogoyqj** [comment]
> `
> 
> * 企业管理-企业详情，编辑收票地址
> * @summary 编辑企业收票信息
> * @param data: ParamsBodyenterpriseManageDetailSaveReceiptPost
> * @param opt ajax config
> * @returns models.EnterprisemanageUpdateEnterpriseBillInfo
>   `
> 
> 我找到了问题的位置，如果有相同的返回类型， api 目录下会复用， 导致其他接口的类型没有生成， 那如果我只想生成类型文件， 如果获知这种复用关系呢

这个需要解析 swagger 了，如果数据结构是复用的，那么相应的 schema $ref 也是会指向同一个 DTO，例如“#/definitions/AbQueryModel”

**Comment by flames519** [comment]
`json
{
    "/currencyGoodsSearch/selectGoodsListByCategory": {
        "post": {
            "parameters": [
                {
                    "name": "CurrencyGoodsSearchSelectGoodsListByCategoryBody",
                    "in": "body",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "object",
                        "properties": {
                            "data": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "goodsCode": {
                                            "type": "string"
                                        },
                                        "goodsId": {
                                            "type": "number"
                                        },
                                        "goodsName": {
                                            "type": "string"
                                        },
                                        "unitName": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "goodsCode",
                                        "goodsId",
                                        "goodsName",
                                        "unitName"
                                    ]
                                }
                            },
                            "pageNum": {
                                "type": "number"
                            },
                            "pageSize": {
                                "type": "number"
                            },
                            "success": {
                                "type": "boolean"
                            },
                            "totalCount": {
                                "type": "number"
                            },
                            "totalPages": {
                                "type": "number"
                            },
                            "code": {
                                "type": "string"
                            },
                            "message": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "data",
                            "code",
                            "success",
                            "totalCount",
                            "pageNum",
                            "pageSize",
                            "totalPages",
                            "message"
                        ]
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "successful operation",
                    "schema": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "type": "object",
                        "properties": {
                            "data": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "dataVersion": {
                                            "type": "number"
                                        },
                                        "goodsCode": {
                                            "type": "string"
                                        },
                                        "goodsId": {
                                            "type": "number"
                                        },
                                        "goodsName": {
                                            "type": "string"
                                        },
                                        "newFlag": {
                                            "type": "boolean"
                                        },
                                        "temGoodsFlag": {
                                            "type": "boolean"
                                        }
                                    },
                                    "required": [
                                        "dataVersion",
                                        "goodsCode",
                                        "goodsId",
                                        "goodsName",
                                        "newFlag",
                                        "temGoodsFlag"
                                    ]
                                }
                            },
                            "pageNum": {
                                "type": "number"
                            },
                            "pageSize": {
                                "type": "number"
                            },
                            "success": {
                                "type": "boolean"
                            },
                            "totalCount": {
                                "type": "number"
                            },
                            "totalPages": {
                                "type": "number"
                            }
                        },
                        "title": "CurrencyGoodsSearchSelectGoodsListByCategory"
                    }
                }
            }
        }
    }
}
`

**Comment by gogoyqj** [comment]
> ```json
> CurrencyGoodsSearchSelectGoodsListByCategoryBody
> ```

额，我用 4.0.2 版本，没有复现你说的这个问题 @flames519
