### ISSUE TITLE
建议支持修改 host 或使用 localhost

### ISSUE THREAD

**Issue by yunsii** [gogoyqj/auto-service#45]
WSL 下通过浏览器 127.0.0.1 不可访问 WSL 下的服务，需要改为 localhost 才行，已经改累了 \_(:з」∠)\_

**Comment by gogoyqj** [comment]
auto-service@4.0.1
```
module.exports = {
  url: './swagger.json',
  ...
  name: 'localhost',
  ...
}
```

**Comment by yunsii** [comment]
> auto-service@4.0.1
> 
> ```
> module.exports = {
>   url: './swagger.json',
>   ...
>   name: 'localhost',
>   ...
> }
> ```

应该是 hostname https://github.com/gogoyqj/auto-service/blob/6d29a74635626984a9c44b0e9669fbe6fa2b308d/src/index.ts#L73 已经试过了
