### ISSUE TITLE
Service 带查询参数生成有误？

### ISSUE THREAD

**Issue by yunsii** [gogoyqj/auto-service#47]
刚从 auto-service@3.4.7 升级到 4.0.1，之前的一个 service 调用为：

`APIS.ShareApi.apiV1ShareFindProjectByShareLinkShareUuidGet`

看了一下现在生成的是 `apiV1ShareFindProjectByShareLinkshareUuidGet`，查询参数没有 upper case 一下？

**Comment by yunsii** [comment]
看了 lock 文件，之前基于 ^3.4.7 安装的其实是 3.6.3 版本，发的应该是这次变更 https://github.com/gogoyqj/auto-service/commit/eebf6e8655fe361ea34546bc637312f1c447784b#diff-85d019f89a8686a2b64166ed2f0972d027a79afc986c6939c9ae8a994716ebe5，已经改变了 jar，之后以及目前的 4.0.1 也没有针对模板中的 {{nickname}} 有什么处理，真是看不懂问题出在哪里了。。。

**Comment by yunsii** [comment]
另外，关于发版还是打相应的 tag 的吧，不然找源码真蛋疼 😂

**Comment by gogoyqj** [comment]
> 刚从 auto-service@3.4.7 升级到 4.0.1，之前的一个 service 调用为：
> 
> `APIS.ShareApi.apiV1ShareFindProjectByShareLinkShareUuidGet`
> 
> 看了一下现在生成的是 `apiV1ShareFindProjectByShareLinkshareUuidGet`，查询参数没有 upper case 一下？

奇怪，确认没有变更输入的 swagger 么？根据 url 生成 method name 的代码没有变动过

https://github.com/gogoyqj/auto-service/blob/master/src/guard.ts#L88

```ts
          api.privateOperationId =
            url
              .replace(prefixReg, '')
              .replace(/(^\/|})/g, '')
              .replace(/[/{_-]{1,}([^/])/g, (mat, u: string) => u.toUpperCase()) +
            methodPrefix +
            method[0].toUpperCase() +
            method.substring(1);
```

**Comment by gogoyqj** [comment]
> 另外，关于发版还是打相应的 tag 的吧，不然找源码真蛋疼 😂

后续会打 tag

**Comment by yunsii** [comment]
yapi 后台**接口路径**定义如下：

`/api/v1/share/findProjectByShareLink/{shareUuid}`

看了 yapi 上次修改是在去年 5 月份了，yapi-swagger.json 对应的描述：

![image](https://user-images.githubusercontent.com/18096089/150747929-12e42a3b-78ea-45ea-9b79-8d2ec1d3a422.png)

生成的函数名称：`apiV1ShareFindProjectByShareLinkshareUuidGet`

是正常的吗？

**Comment by gogoyqj** [comment]
> apiV1ShareFindProjectByShareLinkshareUuidGet

验证了一下，确实有问题：使用 yapi 的情况下，函数名是由 jar 包根据 url 生成的，应该是  v3 比较老的版本和 v4 里使用的 jar 包有些微不一致，尴尬了，，，

需要手动全局替换一下有问题的调用

**Comment by yunsii** [comment]
> 验证了一下，确实有问题：使用 yapi 的情况下，函数名是由 jar 包根据 url 生成的，应该是 v3 比较老的版本和 v4 里使用的 jar 包有些微不一致，尴尬了，，，
> 
> 需要手动全局替换一下有问题的调用

有安排了吗？

**Comment by gogoyqj** [comment]
> > 用的 jar 包有些微不一致，尴尬了，，，
> > 需要手动全局替换一下有问题的调用
> 
> 有安排了吗？

升级到 4.0.2 已修复
