### ISSUE TITLE
mac 运行直接报错？

### ISSUE THREAD

**Issue by javaxiu** [gogoyqj/auto-service#51]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/4281225/158561586-9d80d755-2a21-449c-aa5d-cea1ba456187.png">
如图，不管是在项目下运行 `npx auto -c ./json2server.json` 命令，还是在外层运行 `npx auto -v`，都会报错

**Comment by gogoyqj** [comment]
> <img alt="image" width="556" src="https://user-images.githubusercontent.com/4281225/158561586-9d80d755-2a21-449c-aa5d-cea1ba456187.png">
> 
> 如图，不管是在项目下运行 `npx auto -c ./json2server.json` 命令，还是在外层运行 `npx auto -v`，都会报错

是 `npx autos`，此处少了一个 s
