### ISSUE TITLE
swagger 3.0爆错，看起来是脚本中自动删掉了那个目录，手动创建目录也说找不到

### ISSUE THREAD

**Issue by akan** [gogoyqj/auto-service#55]
➜ npx autos                                                                               
[INFO]: 打开链接 http://127.0.0.1:3007/ 编辑
[ERROR]: gen failed with: [ERROR]: gen failed from
 /usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9.json with
 访问临时目录 /usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9_json 失败
错误信息：Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9_json'

**Comment by gogoyqj** [comment]
> ➜ npx autos [INFO]: 打开链接 http://127.0.0.1:3007/ 编辑 [ERROR]: gen failed with: [ERROR]: gen failed from /usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9.json with 访问临时目录 /usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9_json 失败 错误信息：Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/auto-service/tmp/1ea9c3379bc5fe5674e8665d17eb41e9_json'

据查，是依赖的 swagger-codegen v3 找不到 mustache 模板，修复中
