### ISSUE TITLE
@ajax 如何设置才能引用到？

### ISSUE THREAD

**Issue by Raykid** [gogoyqj/auto-service#59]
大佬你好，我不太清楚如何设置才能正确引用 @ajax 模块，ts 总是报错。谢谢大佬~

![image](https://user-images.githubusercontent.com/6106109/171196929-fe227660-8554-4b0c-84bd-10d6a226056f.png)

**Comment by gogoyqj** [comment]
@Raykid 在项目的 tsconfig.json 里配置配置 '@ajax' 的 path 指向自己的代码实现，ajax 的实现可以参考：https://github.com/e-kit/ekit/blob/master/packages/ajax/src/new-ajax.ts

**Comment by Raykid** [comment]
> 

搞定了，感谢。贴出解决方案图片方便其他人查看

tsconfig.json
![image](https://user-images.githubusercontent.com/6106109/171315843-02102a30-66c6-4339-9a31-a728465c2a8d.png)

webpack.config.js
![image](https://user-images.githubusercontent.com/6106109/171315882-b8036cde-c31c-4884-8960-1798478e4fa3.png)
