### ISSUE TITLE
 YAPI 生成Typescript失败

### ISSUE THREAD

**Issue by canGeEr** [gogoyqj/auto-service#72]
[ERROR]: 基于 YAPI 生成失败: [ERROR]: parse yapi to swagger from https://sr-yapi.woa.com/api/open/plugin/export-full?type=json&pid=148&status=all&token=1168b3818b0d334d16e3605afab5a9a4becc41b80ef2fb7eacebfd4efa03b048 faild with Cannot read properties of undefined (reading 'errcode')
1

基本配置
```json
{
  "url": "yapi-swagger.json",
  "remoteUrl": "https://sr-yapi.woa.com/api/open/plugin/export-full?type=json&pid=148&status=all&token=1168b3818b0d334d16e3605afab5a9a4becc41b80ef2fb7eacebfd4efa03b048",
  "type": "yapi",
  "swaggerParser": {}
}
```

**Comment by canGeEr** [comment]
> @canGeEr 如错误信息提示，在从你们部署的 yapi 服务上下载文档 json 的时候出错了，你试试直接通过 curl 或者 wget 命令看看是否可以读取 json 数据：
> 
> ```shell
> curl https://sr-yapi.woa.com/api/open/plugin/export-full?type=json&pid=148&status=all&token=1168b3818b0d334d16e3605afab5a9a4becc41b80ef2fb7eacebfd4efa03b048
> ```
> 
> 大概率是不能的，需要想办法让这个 url 可以通过 cli 可访问，可能涉及到域名、网关的一些配置



> @canGeEr 如错误信息提示，在从你们部署的 yapi 服务上下载文档 json 的时候出错了，你试试直接通过 curl 或者 wget 命令看看是否可以读取 json 数据：
> 
> ```shell
> curl https://sr-yapi.woa.com/api/open/plugin/export-full?type=json&pid=148&status=all&token=1168b3818b0d334d16e3605afab5a9a4becc41b80ef2fb7eacebfd4efa03b048
> ```
> 
> 大概率是不能的，需要想办法让这个 url 可以通过 cli 可访问，可能涉及到域名、网关的一些配置

我大概懂了，我们公司是用的部署在内网的，需要绕过ioa，
auto-service那能否让发起请求的时候用户可配置cookie呢

**Comment by canGeEr** [comment]
<img width="1240" alt="企业微信截图_4958cead-3ca7-47b4-935f-98cba3d197b3" src="https://user-images.githubusercontent.com/48673499/225594003-e201b797-2218-47ac-9bfb-620fc0f79ed9.png">

这里server没有传递requestConfig，无从下手无法配置该次请求cookie

**Comment by gogoyqj** [comment]
@canGeEr 是支持的，文档里有说明 https://tefe.top/getting-started#224-requestconfig-%E5%8F%82%E6%95%B0

```
{
  requestConfig: {
    headers: {
      cookie: ''
    }
  }
}
```

**Comment by gogoyqj** [comment]
@canGeEr 需要配置 url 和 remoteUrl 两个参数

<img width="757" alt="image" src="https://user-images.githubusercontent.com/1776278/225799060-06d50ab5-d748-48d2-82f7-7fbe2eee1a1e.png">
