### ISSUE TITLE
fomater 不生效

### ISSUE THREAD

**Issue by LiDengHui** [gogoyqj/auto-service#78]
```
{
  swaggerConfig: {
    formater: 'npx prettier {path}/**/**.ts --write --log-level error --with-node-modules'
  },
}

```
不能 生效 没有格式化代码

**Comment by LiDengHui** [comment]
<img width="1606" alt="image" src="https://github.com/gogoyqj/auto-service/assets/8112598/c4f17fdf-3c8b-4672-9283-b4a3bffea142">

在执行的时候 prettier ignore-path 有 .gitignore ， 正好里面有个 node_modules

**Comment by gogoyqj** [comment]
> <img alt="image" width="1606" src="https://user-images.githubusercontent.com/8112598/261524516-c4f17fdf-3c8b-4672-9283-b4a3bffea142.png">
> 在执行的时候 prettier ignore-path 有 .gitignore ， 正好里面有个 node_modules

```
formater:
            'prettier {path}/**/**.ts --write --log-level error --with-node-modules --ignore-path .prettierignore',
```
