### ISSUE TITLE
对整个项目接口生成时，存在部分生成了对应的operationId，但并没有生成对应的models的case；同时也存在大小写异常的case

### ISSUE THREAD

**Issue by BruceCham** [gogoyqj/auto-service#81]

**Comment by BruceCham** [comment]
![lQLPJxRWtIUEjP_NA4DNB3Kw6h4iBI7F3eMFow0iFtlkAQ_1906_896](https://github.com/gogoyqj/auto-service/assets/7899194/0eed0a75-dace-4290-8de1-865e69e0012f)
大小写异常的case

-----------------------

![lQLPKG_32jGa_f_NBCbNBWCwZTaaDreQ3iAFow0iFtlkAA_1376_1062](https://github.com/gogoyqj/auto-service/assets/7899194/21228418-3279-4cb2-9155-bded76027e91)
model未生成的Case

**Comment by gogoyqj** [comment]
> ![lQLPJxRWtIUEjP_NA4DNB3Kw6h4iBI7F3eMFow0iFtlkAQ_1906_896](https://private-user-images.githubusercontent.com/7899194/299984272-0eed0a75-dace-4290-8de1-865e69e0012f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzY4OTIsIm5iZiI6MTcwNjU3NjU5MiwicGF0aCI6Ii83ODk5MTk0LzI5OTk4NDI3Mi0wZWVkMGE3NS1kYWNlLTQyOTAtOGRlMS04NjVlNjllMDAxMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDEwMzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNiOTg1ZWU4ODAyZTRlMzEyN2MyNDQwZjE3NDJkZmFkMTU3M2I4NDhkYzQ4ZGQyNGQwZjEwMTFlZWY3MTMzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QtRxoqgFdur9rOijXKyYQ0IZ0mid_7q6uYZtbRfPCSA) 大小写异常的case
> 
> ![lQLPKG_32jGa_f_NBCbNBWCwZTaaDreQ3iAFow0iFtlkAA_1376_1062](https://private-user-images.githubusercontent.com/7899194/299984363-21228418-3279-4cb2-9155-bded76027e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzY4OTIsIm5iZiI6MTcwNjU3NjU5MiwicGF0aCI6Ii83ODk5MTk0LzI5OTk4NDM2My0yMTIyODQxOC0zMjc5LTRjYjItOTE1NS1iZGVkNzYwMjdlOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDEwMzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNiNmI2ZmRlNTljYjk2ZGIxYjExYmYyMjFmM2VlNDNjOWY2OWVlNmQyMzlmODNkZDAzYWQ1N2I1NzE0ZTA1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hIRqCG25vmKZOiqxKr23HcSZHqYN7qGyQAbyo_C6PDU) model未生成的Case

麻烦把出现问题的、最精简的yapi-swagger.json代码贴一下，我本地跑跑看为啥哈

**Comment by BruceCham** [comment]
@gogoyqj

**Comment by BruceCham** [comment]
@gogoyqj 
还有个问题，生成的request参数，下划线格式自动变成了驼峰式，示例如下
```js
request 参数 audit_district  
生成的文件中变成了 auditDistrict
```

**Comment by gogoyqj** [comment]
收到，我看看

**Comment by gogoyqj** [comment]
@BruceCham

**Comment by BruceCham** [comment]
@gogoyqj model丢失的问题能复现了，好像是两个接口返回的一样时候，可能会造成另外一个没有生成

### json2service.js

```
module.exports = {
  "url": "./swagger.json",
  "swaggerParser": {
    "-o": "src/test",
    "-t": "plugins/types-only"
  },
  "guardConfig": {
    "mode": "strict",
    "validUrlReg": /cungong/g
  }
}
```

### swagger.json

```
{
  "swagger": "2.0",
  "info": {
    "title": "unknown",
    "version": "last",
    "description": "unknown"
  },
  "tags": [
    {
      "name": "cungong",
      "description": "cungongDesc"
    }
  ],
  "basePath": "",
  "schemes": [
    "http"
  ],
  "paths": {
    "/cungong/ai/marktask": {
      "post": {
        "tags": [
          "cungong"
        ],
        "summary": "任务标注",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "formData",
            "required": true,
            "description": "任务 ID",
            "type": "string"
          },
          {
            "name": "mark",
            "in": "formData",
            "required": true,
            "description": "1-正常 2-违规",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "errNo": {
                  "type": "number"
                },
                "errstr": {
                  "type": "string"
                },
                "data": {
                  "type": "number",
                  "description": "记录 ID"
                }
              },
              "title": "CungongAiMarktask"
            }
          }
        },
        "operationId": "cungongAiMarktaskPost"
      }
    },
    "/cungong/ai/addtask": {
      "post": {
        "tags": [
          "cungong"
        ],
        "summary": "新增任务",
        "description": "",
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "name": "title",
            "in": "formData",
            "required": true,
            "description": "限制长度 200",
            "type": "string"
          },
          {
            "name": "demand",
            "in": "formData",
            "required": false,
            "description": "限制长度 200",
            "type": "string"
          },
          {
            "name": "word_count",
            "in": "formData",
            "required": true,
            "description": "字数范围：1：300-500 2:500-800 3:800+",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "errNo": {
                  "type": "number"
                },
                "errstr": {
                  "type": "string"
                },
                "data": {
                  "type": "number",
                  "description": "记录 ID"
                }
              },
              "title": "CungongAiAddtask"
            }
          }
        },
        "operationId": "cungongAiAddtaskPost"
      }
    }
  }
}
```

**Comment by gogoyqj** [comment]
> @gogoyqj model丢失的问题能复现了，好像是两个接口返回的一样时候，可能会造成另外一个没有生成
> 
> ### json2service.js
> ```
> module.exports = {
>   "url": "./swagger.json",
>   "swaggerParser": {
>     "-o": "src/test",
>     "-t": "plugins/types-only"
>   },
>   "guardConfig": {
>     "mode": "strict",
>     "validUrlReg": /cungong/g
>   }
> }
> ```
> 
> ### swagger.json
> ```
> {
>   "swagger": "2.0",
>   "info": {
>     "title": "unknown",
>     "version": "last",
>     "description": "unknown"
>   },
>   "tags": [
>     {
>       "name": "cungong",
>       "description": "cungongDesc"
>     }
>   ],
>   "basePath": "",
>   "schemes": [
>     "http"
>   ],
>   "paths": {
>     "/cungong/ai/marktask": {
>       "post": {
>         "tags": [
>           "cungong"
>         ],
>         "summary": "任务标注",
>         "description": "",
>         "consumes": [
>           "multipart/form-data"
>         ],
>         "parameters": [
>           {
>             "name": "id",
>             "in": "formData",
>             "required": true,
>             "description": "任务 ID",
>             "type": "string"
>           },
>           {
>             "name": "mark",
>             "in": "formData",
>             "required": true,
>             "description": "1-正常 2-违规",
>             "type": "string"
>           }
>         ],
>         "responses": {
>           "200": {
>             "description": "successful operation",
>             "schema": {
>               "$schema": "http://json-schema.org/draft-04/schema#",
>               "type": "object",
>               "properties": {
>                 "errNo": {
>                   "type": "number"
>                 },
>                 "errstr": {
>                   "type": "string"
>                 },
>                 "data": {
>                   "type": "number",
>                   "description": "记录 ID"
>                 }
>               },
>               "title": "CungongAiMarktask"
>             }
>           }
>         },
>         "operationId": "cungongAiMarktaskPost"
>       }
>     },
>     "/cungong/ai/addtask": {
>       "post": {
>         "tags": [
>           "cungong"
>         ],
>         "summary": "新增任务",
>         "description": "",
>         "consumes": [
>           "multipart/form-data"
>         ],
>         "parameters": [
>           {
>             "name": "title",
>             "in": "formData",
>             "required": true,
>             "description": "限制长度 200",
>             "type": "string"
>           },
>           {
>             "name": "demand",
>             "in": "formData",
>             "required": false,
>             "description": "限制长度 200",
>             "type": "string"
>           },
>           {
>             "name": "word_count",
>             "in": "formData",
>             "required": true,
>             "description": "字数范围：1：300-500 2:500-800 3:800+",
>             "type": "string"
>           }
>         ],
>         "responses": {
>           "200": {
>             "description": "successful operation",
>             "schema": {
>               "$schema": "http://json-schema.org/draft-04/schema#",
>               "type": "object",
>               "properties": {
>                 "errNo": {
>                   "type": "number"
>                 },
>                 "errstr": {
>                   "type": "string"
>                 },
>                 "data": {
>                   "type": "number",
>                   "description": "记录 ID"
>                 }
>               },
>               "title": "CungongAiAddtask"
>             }
>           }
>         },
>         "operationId": "cungongAiAddtaskPost"
>       }
>     }
>   }
> }
> ```

这看起来像是 v2 jar的bug，我换成v3就可以了，如果只生成类型的话，可以只用v3（我猜测v2可能有一个合并相同类型的逻辑在）

```
{
"url": "./swagger.json",
  "swaggerParser": {
    "-o": "src/test",
    "-t": "v3/plugins/types-only"
  },
  "guardConfig": {
    "mode": "strict",
    "validUrlReg": /cungong/g
  }
}
```

![image](https://github.com/gogoyqj/auto-service/assets/1776278/46b8085d-b23e-4ba3-a99c-f3b3e2c69d10)

**Comment by BruceCham** [comment]
@gogoyqj 
在配置中加入如下内容，可以解决 v3 里面camel命名的问题。
```
{
   "url": "./swagger.json",
  "swaggerParser": {
    "-o": "src/test",
    "-t": "v3/plugins/types-only",
    "-DmodelPropertyNaming=snake_case": " "
  },
  "guardConfig": {
    "mode": "strict",
    "validUrlReg": /cungong/g
  }
}
```
但还有个问题一直存在：选择 v3/plugins/types-only 时，java generate 没有生成 tmp/*_json下的文件，一直报错，目前v3 types-only无法使用 ...

**Comment by gogoyqj** [comment]
> @gogoyqj 在配置中加入如下内容，可以解决 v3 里面camel命名的问题。
> 
> ```
> {
>    "url": "./swagger.json",
>   "swaggerParser": {
>     "-o": "src/test",
>     "-t": "v3/plugins/types-only",
>     "-DmodelPropertyNaming=snake_case": " "
>   },
>   "guardConfig": {
>     "mode": "strict",
>     "validUrlReg": /cungong/g
>   }
> }
> ```
> 
> 但还有个问题一直存在：选择 v3/plugins/types-only 时，java generate 没有生成 tmp/*_json下的文件，一直报错，目前v3 types-only无法使用 ... #55

@BruceCham  为何我这边尝试是可以的：

```js
module.exports = {
  "url": "./swagger.json",
  "swaggerParser": {
    "-o": "src/test",
    "-t": "v3/plugins/types-only",
    "-DmodelPropertyNaming=snake_case": "",
  },
  "guardConfig": {
    "mode": "strict",
    "validUrlReg": /cungong/g
  }
}
```

![image](https://github.com/gogoyqj/auto-service/assets/1776278/11cfcaf3-e9aa-4a29-b91e-204e896c0768)

**Comment by BruceCham** [comment]
@gogoyqj https://github.com/gogoyqj/auto-service/issues/82 重新整理到新的issue了
